import PDFDocument from "pdfkit";
import Registration from "../models/registration.js";

export const downloadTicket = async (req, res) => {
  try {
    const registration = await Registration.findById(
      req.params.registrationId
    )
      .populate("event")
      .populate("user");

    if (!registration) {
      return res.status(404).json({
        success: false,
        message: "Ticket not found",
      });
    }

    const doc = new PDFDocument({
      size: "A4",
      margin: 40,
    });

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=ticket-${registration.ticketId}.pdf`
    );

    doc.pipe(res);

    // Header
    doc
      .fontSize(26)
      .text("EVENT PASS", {
        align: "center",
      });

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .text("Generated by EventFlow", {
        align: "center",
      });

    doc.moveDown(2);

    // Ticket Box
    doc
      .roundedRect(40, 120, 520, 250, 10)
      .stroke();

    doc.fontSize(18).text(
      registration.event.title,
      60,
      140
    );

    doc.moveDown();

    doc.fontSize(12);

    doc.text(
      `Date: ${new Date(
        registration.event.date
      ).toLocaleString()}`,
      60,
      180
    );

    doc.text(
      `Location: ${registration.event.location}`,
      60,
      205
    );

    doc.text(
      `Ticket Type: ${registration.ticketType}`,
      60,
      230
    );

    doc.text(
      `Ticket ID: ${registration.ticketId}`,
      60,
      255
    );

    doc.text(
      `Price: ₹${registration.price}`,
      60,
      280
    );

    doc.text(
      `Holder: ${
        registration.user?.name || "User"
      }`,
      60,
      305
    );

    // QR Code
    if (registration.qrCodeDataUrl) {
      const qrBuffer = Buffer.from(
        registration.qrCodeDataUrl.replace(
          /^data:image\/png;base64,/,
          ""
        ),
        "base64"
      );

      doc.image(qrBuffer, 390, 150, {
        width: 120,
      });
    }

    // Barcode
    if (registration.barcodeDataUrl) {
      const barcodeBuffer = Buffer.from(
        registration.barcodeDataUrl.replace(
          /^data:image\/png;base64,/,
          ""
        ),
        "base64"
      );

      doc.image(barcodeBuffer, 60, 390, {
        width: 450,
      });
    }

    // Footer
    doc.moveDown(8);

    doc
      .fontSize(10)
      .text(
        "Please carry this ticket during the event.",
        {
          align: "center",
        }
      );

    doc.end();
  } catch (error) {
    console.log(error);

    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};